title: RiveM Docs
description: Strona na której znajdziesz całą naszą dokumentację
theme: just-the-docs

url: https://mojzeszek12.github.io/rivem/

footer_content: "Na stronie zmiany pojawiają się często. Pamiętaj, by być na bieżąco."
color_scheme: dark